// @fluxbase/functions — embedded by the Flux CLI (no npm install needed)
// Do not edit this file; it is regenerated on `flux function create`.
// This mirrors packages/functions/src/types.ts — keep them in sync.

export interface Schema<T = unknown> {
  parse(data: unknown): T;
  safeParse(data: unknown): { success: true; data: T } | { success: false; error: unknown };
}

export interface FluxSecrets {
  get(key: string): string | null;
}

export interface FluxQueue {
  push(
    functionName: string,
    payload: unknown,
    opts?: { delay?: string; idempotencyKey?: string },
  ): Promise<{ jobId: string }>;
}

export interface FluxFunction {
  invoke(name: string, payload: unknown): Promise<unknown>;
}

export interface FluxFetch {
  (url: string, options?: {
    method?:  string;
    headers?: Record<string, string>;
    body?:    string;
  }): Promise<{
    status:  number;
    ok:      boolean;
    headers: Record<string, string>;
    text(): Promise<string>;
    json(): Promise<unknown>;
  }>;
}

export interface FluxDb {
  query(sql: string, params?: unknown[]): Promise<unknown[]>;
  execute(sql: string, params?: unknown[]): Promise<unknown[]>;
  [table: string]: unknown;
}

export interface FluxTools {
  run(toolName: string, input: Record<string, unknown>): Promise<Record<string, unknown>>;
}

export interface FluxWorkflow {
  run(
    steps: Array<{ name: string; fn: (ctx: FluxContext, previous: Record<string, unknown>) => Promise<unknown> }>,
    options?: { continueOnError?: boolean },
  ): Promise<Record<string, unknown>>;
  parallel(
    steps: Array<{ name: string; fn: (ctx: FluxContext) => Promise<unknown> }>,
  ): Promise<Record<string, unknown>>;
}

export interface FluxContext {
  payload:  unknown;
  secrets:  FluxSecrets;
  env:      Record<string, string>;
  db:       FluxDb;
  queue:    FluxQueue;
  function: FluxFunction;
  fetch:    FluxFetch;
  tools:    FluxTools;
  workflow: FluxWorkflow;
  log(message: string, level?: "info" | "warn" | "error"): void;
  sleep(ms: number): Promise<void>;
  uuid(): string;
  nanoid(size?: number): string;
}

export interface HandlerArgs<TInput = unknown> {
  input: TInput;
  ctx: FluxContext;
}

export interface DefineFunctionOptions<TInput = unknown, TOutput = unknown> {
  name: string;
  description?: string;
  input?: Schema<TInput>;
  output?: Schema<TOutput>;
  handler: (args: HandlerArgs<TInput>) => Promise<TOutput>;
}

export interface FunctionDefinition<TInput = unknown, TOutput = unknown> {
  readonly __fluxbase: true;
  readonly metadata: {
    name: string;
    description?: string;
    input_schema: Record<string, unknown> | null;
    output_schema: Record<string, unknown> | null;
  };
  execute(payload: unknown, context: FluxContext): Promise<TOutput>;
}

export function defineFunction<TInput = unknown, TOutput = unknown>(
  options: DefineFunctionOptions<TInput, TOutput>,
): FunctionDefinition<TInput, TOutput> {
  const { name, description, input: inputSchema, output: outputSchema, handler } = options;
  return {
    __fluxbase: true,
    metadata: { name, description: description, input_schema: null, output_schema: null },
    async execute(payload: unknown, context: FluxContext): Promise<TOutput> {
      const input = inputSchema ? inputSchema.parse(payload) : (payload as TInput);
      const output = await handler({ input, ctx: context });
      if (outputSchema) outputSchema.parse(output);
      return output;
    },
  };
}
