// @fluxbase/functions — embedded by the Flux CLI (no npm install needed)
// Do not edit this file; it is regenerated on `flux function create`.

export interface Schema<T = unknown> {
  parse(data: unknown): T;
  safeParse(data: unknown): { success: true; data: T } | { success: false; error: unknown };
}

export interface FluxSecrets {
  get(key: string): string | null;
}

export interface FluxTools {
  run(toolName: string, input: Record<string, unknown>): Promise<Record<string, unknown>>;
}

export interface FluxWorkflow {
  run(
    steps: Array<{ name: string; fn: (ctx: FluxContext, previous: Record<string, unknown>) => Promise<unknown> }>,
    options?: { continueOnError?: boolean },
  ): Promise<Record<string, unknown>>;
  parallel(
    steps: Array<{ name: string; fn: (ctx: FluxContext) => Promise<unknown> }>,
  ): Promise<Record<string, unknown>>;
}

export interface FluxAgentResult {
  answer: string;
  steps: number;
  output: Record<string, unknown> | null;
}

export interface FluxAgent {
  run(options: { goal: string; tools?: string[]; maxSteps?: number }): Promise<FluxAgentResult>;
}

export interface FluxContext {
  payload: unknown;
  secrets: FluxSecrets;
  env: Record<string, string>;
  log(message: string, level?: "info" | "warn" | "error"): void;
  tools: FluxTools;
  workflow: FluxWorkflow;
  agent: FluxAgent;
  db: Record<string, {
    find(where?: Record<string, unknown>): Promise<unknown[]>;
    findOne(where?: Record<string, unknown>): Promise<unknown | null>;
    insert(data: Record<string, unknown>): Promise<unknown>;
    update(where: Record<string, unknown>, data: Record<string, unknown>): Promise<unknown[]>;
    delete(where: Record<string, unknown>): Promise<void>;
  }>;
  functions: Record<string, (input: unknown) => Promise<unknown>>;
}

export interface HandlerArgs<TInput = unknown> {
  input: TInput;
  ctx: FluxContext;
}

export interface DefineFunctionOptions<TInput = unknown, TOutput = unknown> {
  name: string;
  description?: string;
  input?: Schema<TInput>;
  output?: Schema<TOutput>;
  handler: (args: HandlerArgs<TInput>) => Promise<TOutput>;
}

export interface FunctionDefinition<TInput = unknown, TOutput = unknown> {
  readonly __fluxbase: true;
  readonly metadata: {
    name: string;
    description?: string;
    input_schema: Record<string, unknown> | null;
    output_schema: Record<string, unknown> | null;
  };
  execute(payload: unknown, context: FluxContext): Promise<TOutput>;
}

export function defineFunction<TInput = unknown, TOutput = unknown>(
  options: DefineFunctionOptions<TInput, TOutput>,
): FunctionDefinition<TInput, TOutput> {
  const { name, description, input: inputSchema, output: outputSchema, handler } = options;
  return {
    __fluxbase: true,
    metadata: { name, description: description, input_schema: null, output_schema: null },
    async execute(payload: unknown, context: FluxContext): Promise<TOutput> {
      const input = inputSchema ? inputSchema.parse(payload) : (payload as TInput);
      const output = await handler({ input, ctx: context });
      if (outputSchema) outputSchema.parse(output);
      return output;
    },
  };
}
