/// TypeScript SDK generator.
///
/// GET /sdk/typescript
///
/// Introspects the current project's schema graph (tables + columns +
/// relationships + functions) and emits a `.ts` source file that:
///
///   1.  Declares a TypeScript interface per table (`User`, `Post`, …)
///   2.  Derives `Insert<T>` and `Update<T>` utility types
///   3.  Declares typed input/output interfaces per function
///   4.  Augments the `@fluxbase/sdk` module so the `flux.db.*` and
///       `flux.functions.*` proxies are fully typed
///   5.  Re-exports `createClient` for convenience
///
/// The generated file can be committed or included in a build step — no
/// separate code-gen CLI is required.
use axum::{
    extract::{Extension, State},
    http::{header, HeaderMap},
    response::{IntoResponse, Response},
};
use serde_json::Value;
use sqlx::Row;

use crate::{
    types::{context::RequestContext, response::ApiError},
    AppState,
};

use super::schema::forward_headers;

// ─── Handler ─────────────────────────────────────────────────────────────────

/// GET /sdk/typescript
pub async fn typescript(
    State(state): State<AppState>,
    Extension(ctx): Extension<RequestContext>,
    headers: HeaderMap,
) -> Result<Response, ApiError> {
    let project_id = ctx
        .project_id
        .ok_or_else(|| ApiError::bad_request("missing_project"))?;

    // ── Fetch DB schema from Data Engine ──────────────────────────────────
    let de_url = format!("{}/db/schema", state.data_engine_url);
    let de_resp = state
        .http_client
        .get(&de_url)
        .headers(forward_headers(&headers))
        .send()
        .await
        .map_err(|e| ApiError::internal(&format!("data_engine_unreachable: {}", e)))?;

    let db_schema: Value = de_resp
        .json()
        .await
        .map_err(|e| ApiError::internal(&format!("data_engine_parse: {}", e)))?;

    // ── Fetch function definitions ─────────────────────────────────────────
    let funcs = sqlx::query(
        "SELECT name, description, input_schema, output_schema \
         FROM functions WHERE project_id = $1 ORDER BY name",
    )
    .bind(project_id)
    .fetch_all(&state.pool)
    .await
    .map_err(|_| ApiError::internal("db_error"))?;

    let func_values: Vec<Value> = funcs
        .into_iter()
        .map(|f| {
            serde_json::json!({
                "name":          f.get::<String, _>("name"),
                "description":   f.get::<Option<String>, _>("description"),
                "input_schema":  f.get::<Option<serde_json::Value>, _>("input_schema"),
                "output_schema": f.get::<Option<serde_json::Value>, _>("output_schema"),
            })
        })
        .collect();

    let sdk = generate_sdk(&db_schema, &func_values);

    Ok((
        [(header::CONTENT_TYPE, "application/typescript; charset=utf-8")],
        sdk,
    )
        .into_response())
}

// ─── Generation helpers ───────────────────────────────────────────────────────

/// Map a Fluxbase column type to the appropriate TypeScript primitive.
fn fb_type_to_ts(fb_type: &str) -> &'static str {
    match fb_type {
        "text" | "varchar" | "bpchar" | "uuid" | "date" | "timestamp"
        | "timestamptz" | "interval" | "citext" | "char" | "name" => "string",
        "int2" | "int4" | "int8" | "float4" | "float8" | "numeric" | "money" => "number",
        "bool" => "boolean",
        "jsonb" | "json" => "unknown",
        "file" => "FluxFile",
        "computed" => "unknown",
        t if t.starts_with('_') => match &t[1..] {
            "text" | "varchar" | "uuid" => "string[]",
            "int4" | "int8" | "float8" | "numeric" => "number[]",
            "bool" => "boolean[]",
            _ => "unknown[]",
        },
        _ => "unknown",
    }
}

/// Convert `snake_case` → `PascalCase` for TypeScript interface names.
fn to_pascal(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Determine whether a column should be optional in the generated interface.
/// Files, metadata fields, and common auto-set columns are optional.
fn is_optional_col(col: &str, fb_type: &str) -> bool {
    fb_type == "file"
        || fb_type == "computed"
        || matches!(
            col,
            "updated_at"
                | "deleted_at"
                | "description"
                | "meta"
                | "tags"
                | "avatar"
                | "cover"
        )
}

/// Recursively convert a JSON Schema node (as generated by the Zod walker in
/// `@fluxbase/functions`) to a TypeScript type string.
fn json_schema_to_ts(schema: &Value, depth: usize) -> String {
    let pad = "  ".repeat(depth);
    let Value::Object(obj) = schema else {
        return "unknown".to_string();
    };

    let type_name = obj
        .get("type")
        .and_then(|t| t.as_str())
        .unwrap_or("");

    match type_name {
        "string" => {
            if let Some(enums) = obj.get("enum").and_then(|e| e.as_array()) {
                let variants: Vec<String> = enums
                    .iter()
                    .filter_map(|v| v.as_str())
                    .map(|v| format!("\"{}\"", v))
                    .collect();
                if !variants.is_empty() {
                    return variants.join(" | ");
                }
            }
            "string".to_string()
        }
        "number" | "integer" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        "null" | "undefined" => "null".to_string(),
        "array" => {
            let items_ts = obj
                .get("items")
                .map(|i| json_schema_to_ts(i, depth))
                .unwrap_or_else(|| "unknown".to_string());
            format!("{}[]", items_ts)
        }
        "object" | "" => {
            if let Some(props) = obj.get("properties").and_then(|p| p.as_object()) {
                let required: Vec<&str> = obj
                    .get("required")
                    .and_then(|r| r.as_array())
                    .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
                    .unwrap_or_default();

                if props.is_empty() {
                    return "Record<string, unknown>".to_string();
                }

                let fields: Vec<String> = props
                    .iter()
                    .map(|(k, v)| {
                        let optional = !required.contains(&k.as_str());
                        let ts = json_schema_to_ts(v, depth + 1);
                        let sep = if optional { "?: " } else { ": " };
                        format!("{}  {}{}{};", pad, k, sep, ts)
                    })
                    .collect();

                format!("{{\n{}\n{}}}", fields.join("\n"), pad)
            } else {
                "Record<string, unknown>".to_string()
            }
        }
        _ => "unknown".to_string(),
    }
}

/// Core generation function. Accepts the raw schema graph values and produces
/// the complete TypeScript SDK source string.
fn generate_sdk(db_schema: &Value, functions: &[Value]) -> String {
    let empty = Value::Array(vec![]);
    let tables = db_schema.get("tables").unwrap_or(&empty);
    let columns = db_schema.get("columns").unwrap_or(&empty);
    let relationships = db_schema.get("relationships").unwrap_or(&empty);

    let mut out = String::with_capacity(8192);

    // ── File header ───────────────────────────────────────────────────────
    out.push_str(
        "// Auto-generated by Fluxbase SDK Generator — do not edit manually.\n\
         // Regenerate: GET /sdk/typescript\n\
         // prettier-ignore-start\n\
         /* eslint-disable */\n\n",
    );

    // ── FluxFile primitive ────────────────────────────────────────────────
    out.push_str("export type FluxFile = {\n");
    out.push_str("  url: string;\n");
    out.push_str("  key: string;\n");
    out.push_str("  size: number;\n");
    out.push_str("  mime_type: string;\n");
    out.push_str("};\n\n");

    // ── Build table → columns map ─────────────────────────────────────────
    // BTreeMap ensures deterministic ordering in the output.
    let mut table_cols: std::collections::BTreeMap<
        String,              // table name
        Vec<(String, String)>,  // (column, fb_type)
    > = std::collections::BTreeMap::new();

    if let Some(cols) = columns.as_array() {
        for col in cols {
            let table = col
                .get("table")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let column = col
                .get("column")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let fb_type = col
                .get("fb_type")
                .and_then(|v| v.as_str())
                .unwrap_or("text")
                .to_string();
            if !table.is_empty() && !column.is_empty() {
                table_cols
                    .entry(table)
                    .or_default()
                    .push((column, fb_type));
            }
        }
    }

    // ── Build relationship map: table → [(alias, to_table, kind)] ─────────
    let mut rels: std::collections::BTreeMap<String, Vec<(String, String, String)>> =
        std::collections::BTreeMap::new();

    if let Some(rel_arr) = relationships.as_array() {
        for rel in rel_arr {
            let from = rel
                .get("from_table")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let alias = rel
                .get("alias")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let to = rel
                .get("to_table")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let kind = rel
                .get("relationship")
                .and_then(|v| v.as_str())
                .unwrap_or("one_to_many")
                .to_string();
            if !from.is_empty() && !alias.is_empty() {
                rels.entry(from).or_default().push((alias, to, kind));
            }
        }
    }

    // ── Generate table interfaces ─────────────────────────────────────────
    let mut table_names: Vec<String> = Vec::new();

    if let Some(tbls) = tables.as_array() {
        for tbl in tbls {
            let Some(name) = tbl.get("table").and_then(|v| v.as_str()) else {
                continue;
            };
            table_names.push(name.to_string());
            let iface = to_pascal(name);

            // Main interface
            out.push_str(&format!("export interface {} {{\n", iface));
            if let Some(cols) = table_cols.get(name) {
                for (col, fb_type) in cols {
                    let ts = fb_type_to_ts(fb_type);
                    let opt = is_optional_col(col, fb_type);
                    let sep = if opt { "?: " } else { ": " };
                    out.push_str(&format!("  {}{}{};\n", col, sep, ts));
                }
            }
            // Relationship fields (optional nested objects)
            if let Some(table_rels) = rels.get(name) {
                for (alias, to_table, kind) in table_rels {
                    let rel_iface = to_pascal(to_table);
                    let ts = if kind.contains("many") {
                        format!("{}[]", rel_iface)
                    } else {
                        rel_iface.clone()
                    };
                    out.push_str(&format!("  {}?: {};\n", alias, ts));
                }
            }
            out.push_str("}\n\n");

            // Insert / Update utility types
            out.push_str(&format!(
                "export type Insert{} = Omit<{}, \"id\" | \"created_at\" | \"updated_at\" | \"deleted_at\">;\n",
                iface, iface
            ));
            out.push_str(&format!(
                "export type Update{} = Partial<Insert{}>;\n\n",
                iface, iface
            ));
        }
    }

    // ── Generate function types ───────────────────────────────────────────
    let mut func_names: Vec<String> = Vec::new();

    for func in functions {
        let Some(name) = func.get("name").and_then(|v| v.as_str()) else {
            continue;
        };
        func_names.push(name.to_string());
        let iface = to_pascal(name);

        if let Some(desc) = func.get("description").and_then(|v| v.as_str()) {
            if !desc.is_empty() {
                out.push_str(&format!("/** {} */\n", desc));
            }
        }

        let input_ts = match func.get("input_schema").map(|s| json_schema_to_ts(s, 0)) {
            Some(ts) if ts != "unknown" => ts,
            _ => "Record<string, unknown>".to_string(),
        };
        out.push_str(&format!("export type {}Input = {};\n", iface, input_ts));

        let output_ts = match func.get("output_schema").map(|s| json_schema_to_ts(s, 0)) {
            Some(ts) if ts != "unknown" => ts,
            _ => "unknown".to_string(),
        };
        out.push_str(&format!("export type {}Output = {};\n\n", iface, output_ts));
    }

    // ── Module augmentation ───────────────────────────────────────────────
    // Augments the `@fluxbase/sdk` module so the dynamically-proxied
    // `flux.db.*` and `flux.functions.*` objects are fully typed.
    out.push_str("declare module \"@fluxbase/sdk\" {\n");

    // FluxbaseDB augmentation
    out.push_str("  interface FluxbaseDB {\n");
    for name in &table_names {
        let iface = to_pascal(name);
        out.push_str(&format!(
            "    {}: import(\"@fluxbase/sdk\").TableClient<{}, Insert{}, Update{}>;\n",
            name, iface, iface, iface
        ));
    }
    out.push_str("  }\n\n");

    // FluxbaseFunctions augmentation
    out.push_str("  interface FluxbaseFunctions {\n");
    for name in &func_names {
        let iface = to_pascal(name);
        out.push_str(&format!(
            "    {}(input: {}Input): Promise<{}Output>;\n",
            name, iface, iface
        ));
    }
    out.push_str("  }\n}\n\n");

    // ── Convenience re-export ─────────────────────────────────────────────
    out.push_str("export { createClient } from \"@fluxbase/sdk\";\n");
    out.push_str("// prettier-ignore-end\n");

    out
}
