use std::path::{Path, PathBuf};
use std::time::Instant;

use anyhow::{bail, Context, Result};
use clap::Parser;
use deno_ast::{EmitOptions, MediaType, ParseParams, TranspileModuleOptions, TranspileOptions};
use runtime::isolate_pool::ExecutionContext;

#[derive(Parser, Debug)]
#[command(name = "flux-runtime")]
#[command(
    about = "Flux runtime — runs user JS handlers and streams execution records to flux-server"
)]
struct Args {
    #[arg(long, value_name = "FILE")]
    entry: Option<String>,

    /// Deterministic build artifact generated by `flux build`.
    #[arg(long, value_name = "FILE")]
    artifact: Option<String>,

    /// URL of the flux-server gRPC endpoint.
    #[arg(
        long,
        value_name = "URL",
        env = "FLUX_SERVER_URL",
        default_value = "http://127.0.0.1:3003"
    )]
    server_url: String,

    /// Service token for authenticating with flux-server.
    #[arg(
        long,
        env = "FLUX_SERVICE_TOKEN",
        value_name = "TOKEN",
        default_value = ""
    )]
    token: String,

    /// HTTP listen host.
    #[arg(long, env = "HOST", default_value = "0.0.0.0")]
    host: String,

    /// HTTP listen port.
    #[arg(long, env = "PORT", default_value_t = 3000)]
    port: u16,

    /// Number of V8 isolates to keep warm.
    #[arg(long, default_value_t = 16)]
    isolate_pool_size: usize,

    /// Force the runtime to stay alive as an HTTP listener even if Deno.serve()
    /// was not called (e.g. to serve an exported default handler).
    #[arg(long)]
    serve: bool,

    /// JSON input passed to the exported default handler for a one-off execution.
    /// If provided, the runtime will execute the handler once and then exit.
    #[arg(long, value_name = "JSON")]
    script_input: Option<String>,

    /// Project ID for this execution.
    #[arg(long, env = "FLUX_PROJECT_ID", value_name = "ID")]
    project_id: Option<String>,

    /// Print raw console logs from the replayed execution.
    #[arg(long)]
    verbose: bool,

    /// Execution ID to replay. If provided, the runtime fetches recorded
    /// checkpoints for this ID and runs the local code against them.
    #[arg(long, value_name = "ID")]
    replay: Option<String>,

    /// Start as a persistent HTTP gateway. No entry file required; each
    /// inbound request must supply its own `artifact` JSON field.
    #[arg(long)]
    gateway: bool,
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .init();

    let args = Args::parse();

    // Gateway mode: no entry file needed. Requests supply their own artifact.
    if args.gateway {
        let placeholder_js = "export default function _gateway(ctx) { \n\
            return ctx.json({ \n\
                error: 'no_artifact_loaded', \n\
                message: 'The runtime is in gateway mode but no function artifact has been hot-swapped yet.', \n\
                tip: 'Check flux-executor logs for hot-reload failures or verify FLUX_SERVICE_TOKEN.' \n\
            }, 503);\n\
        }";
        let artifact = runtime::build_artifact("_gateway", placeholder_js.to_string());
        tracing::info!(
            "Starting flux-runtime in gateway mode on port {}",
            args.port
        );
        runtime::run_http_runtime(
            runtime::HttpRuntimeConfig {
                host: args.host,
                port: args.port,
                route_name: "_gateway".to_string(),
                isolate_pool_size: 2, // minimal pool; real work done per-request
                project_id: args.project_id,
                server_url: args.server_url,
                service_token: args.token,
            },
            artifact,
        )
        .await?;
        return Ok(());
    }

    let (artifact, route_name) = if let Some(artifact_path) = &args.artifact {
        let artifact = runtime::load_built_artifact_from_file(artifact_path)
            .map_err(|err| anyhow::anyhow!(err))?;
        let route_name = match &artifact {
            runtime::RuntimeArtifact::Built(artifact) => artifact.route_name.clone(),
            runtime::RuntimeArtifact::Inline(_) => {
                unreachable!("built artifact loader returned inline artifact")
            }
        };
        (artifact, route_name)
    } else {
        let entry_fallback = ["index.js", "src/index.ts", "src/index.js", "index.ts"];
        let entry = if let Some(e) = &args.entry {
            PathBuf::from(e)
        } else {
            entry_fallback
                .iter()
                .map(PathBuf::from)
                .find(|p| p.exists())
                .unwrap_or_else(|| PathBuf::from("index.js"))
        };

        if !entry.exists() {
            bail!(
                "entry file not found: {}. Tried: {}",
                entry.display(),
                entry_fallback.join(", ")
            );
        }

        match extension(&entry).as_deref() {
            Some("js") | Some("mjs") | Some("cjs") | Some("ts") | Some("tsx") => {}
            _ => bail!("unsupported entry file extension: {}", entry.display()),
        }

        let canonical_entry = entry
            .canonicalize()
            .with_context(|| format!("failed to resolve entry path: {}", entry.display()))?;

        // If we have a script_input, we skip the CWD check because the runner
        // might write a temp file.
        if args.script_input.is_none() {
            let cwd = std::env::current_dir().context("failed to read current directory")?;
            let canonical_cwd = cwd
                .canonicalize()
                .context("failed to resolve current directory")?;
            if !canonical_entry.starts_with(&canonical_cwd) {
                bail!(
                    "entry file must be within the working directory: {} is outside {}",
                    canonical_entry.display(),
                    canonical_cwd.display()
                );
            }
        }

        let name = entry
            .file_name()
            .and_then(|v| v.to_str())
            .ok_or_else(|| anyhow::anyhow!("invalid entry file name: {}", entry.display()))?;

        let code = load_entry_code(&entry)?;
        let artifact = runtime::build_artifact(name, code);
        let route_name = entry
            .file_stem()
            .and_then(|v| v.to_str())
            .unwrap_or("index")
            .to_string();

        (artifact, route_name)
    };

    if args.replay.is_none() {
        println!("server:   {}", args.server_url);
        if let Some(path) = &args.artifact {
            println!("artifact: {}", path);
        } else if let Some(entry) = &args.entry {
            println!("entry:    {}", entry);
        } else {
            println!("entry:    (auto)");
        }
    }
    if args.replay.is_none() {
        println!("hash:     {}", artifact.code_version());
        println!("bytes:    {}", artifact.size_bytes());
    }

    // Boot the project to detect if it's a server or a one-shot handler.
    let mut boot_context = ExecutionContext::with_project(
        artifact.code_version().to_string(),
        args.project_id.clone(),
    );
    boot_context.verbose = args.verbose;

    let mut recorded_checkpoints = Vec::new();
    let mut replay_input = args.script_input.clone();

    let mut replay_trace = None;

    if let Some(ref replay_id) = args.replay {
        if args.token.is_empty() {
            // println!("replay:   {}", replay_id);
        }
        let trace =
            runtime::server_client::get_trace(&args.server_url, &args.token, replay_id).await?;
        recorded_checkpoints = trace
            .checkpoints
            .iter()
            .map(|cp| runtime::deno_runtime::FetchCheckpoint {
                call_index: cp.call_index as u32,
                boundary: cp.boundary.clone(),
                url: String::new(),
                method: String::new(),
                request: serde_json::from_slice(&cp.request).unwrap_or(serde_json::Value::Null),
                response: serde_json::from_slice(&cp.response).unwrap_or(serde_json::Value::Null),
                duration_ms: cp.duration_ms,
            })
            .collect();

        boot_context.mode = runtime::deno_runtime::ExecutionMode::Replay;

        if replay_input.is_none() {
            replay_input = Some(trace.request_json.clone());
        }
        replay_trace = Some(trace);
    }

    if args.verbose {
        println!(
            "[boot] execution_id={} request_id={}",
            boot_context.execution_id, boot_context.request_id
        );
    }

    let boot = runtime::boot_runtime_artifact(&artifact, boot_context.clone()).await?;

    let is_server_mode = boot.is_server_mode;
    let has_handler = boot.has_handler;

    if args.replay.is_none() {
        if is_server_mode {
            println!(
                "runtime:  http://{}:{}/ (Deno.serve mode)",
                args.host, args.port
            );
        } else if has_handler {
            println!(
                "runtime:  http://{}:{}/{} (handler mode)",
                args.host, args.port, route_name
            );
        }
    }

    // Capture the boot result if recording is enabled.
    if !args.token.is_empty() {
        let _ = runtime::server_client::record_execution(
            &args.server_url,
            &args.token,
            runtime::server_client::ExecutionEnvelope {
                method: "BOOT".to_string(),
                path: "/__boot".to_string(),
                project_id: args.project_id.clone(),
                request_json: serde_json::json!({ "phase": "boot" }),
                result: boot.result.clone(),
            },
        )
        .await;
    }

    if let Some(error) = boot.result.error.as_ref() {
        eprintln!("error: boot failed: {error}");
        if !is_server_mode && !has_handler {
            return Ok(());
        }
    } // 1. If script_input or replay is provided, execute the handler once and exit.
    if let Some(input_str) = &replay_input {
        if !has_handler && !is_server_mode {
            return Ok(());
        }

        let mut isolate = runtime::JsIsolate::new_from_any_artifact(&artifact, 0).await?;
        let started = Instant::now();

        let execution = if is_server_mode {
            let trace = replay_trace
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("replay trace missing for server-mode replay"))?;

            // Intelligent unpacking: Flux HTTP executions record an envelope.
            // If the request_json looks like an envelope, extract the real body and headers.
            let (body, headers_json) = if let Ok(envelope) =
                serde_json::from_str::<serde_json::Value>(&trace.request_json)
            {
                if envelope.get("method").is_some()
                    && envelope.get("url").is_some()
                    && envelope.get("body").is_some()
                {
                    let b = envelope
                        .get("body")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .to_string();
                    let h = serde_json::to_string(
                        envelope.get("headers").unwrap_or(&serde_json::json!([])),
                    )
                    .unwrap_or_else(|_| "[]".to_string());
                    (b, h)
                } else {
                    (
                        trace.request_json.clone(),
                        "[[\"content-type\", \"application/json\"]]".to_string(),
                    )
                }
            } else {
                (
                    trace.request_json.clone(),
                    "[[\"content-type\", \"application/json\"]]".to_string(),
                )
            };

            let original_failed = trace.status != "ok";
            let net_req = runtime::deno_runtime::NetRequest {
                req_id: boot_context.request_id.clone(),
                method: trace.method.clone(),
                url: format!("http://{}{}", args.host, trace.path),
                headers_json: headers_json.clone(),
                body: body.clone(),
            };

            let res = isolate
                .dispatch_request_with_recorded(boot_context.clone(), net_req, recorded_checkpoints)
                .await?;

            // Detect boundary stop — the sentinel signals that replay stopped cleanly at an IO boundary
            let boundary_stop: Option<String> = res.boundary_stop.clone().or_else(|| {
                res.error
                    .as_deref()
                    .and_then(|e| e.strip_prefix("__FLUX_BOUNDARY_STOP:"))
                    .map(|s| s.split(':').next().unwrap_or(s).to_string())
            });

            let mut execution = runtime::isolate_pool::ExecutionResult {
                execution_id: boot_context.execution_id.clone(),
                request_id: boot_context.request_id.clone(),
                project_id: args.project_id.clone(),
                code_version: boot_context.code_version.clone(),
                status: if boundary_stop.is_some() {
                    "stopped".to_string()
                } else if res.response.status >= 400 {
                    "error".to_string()
                } else {
                    "ok".to_string()
                },
                body: serde_json::json!({
                    "status": res.response.status,
                    "headers": res.response.headers,
                    "body": res.response.body,
                }),
                error: if boundary_stop.is_some() {
                    None
                } else {
                    res.error
                },
                duration_ms: std::cmp::max(1, started.elapsed().as_millis() as i32),
                checkpoints: res.checkpoints,
                logs: res.logs,
                has_live_io: false,
                boundary_stop: None,

                // Advanced Telemetry
                client_ip: None,
                user_agent: None,
                request_method: Some(trace.method.clone()),
                request_headers: Some(serde_json::Value::String(headers_json.clone())),
                request_body: Some(body.clone()),
                response_status: Some(res.response.status as i32),
                response_body: Some(res.response.body.clone()),
                error_name: res.error_name,
                error_message: res.error_message,
                error_stack: res.error_stack,
                error_phase: res.error_phase,
                is_user_code: res.is_user_code,
                error_source: res.error_source,
                error_type: res.error_type,
                error_fingerprint: None,
            };

            // Robust error capture: fallback to logs if error is missing but status is error
            if execution.error.is_none() && execution.status == "error" {
                if let Some(error_log) = execution.logs.iter().rev().find(|l| l.level == "error") {
                    execution.error = Some(error_log.message.clone());
                } else if let Some(warn_log) =
                    execution.logs.iter().rev().find(|l| l.level == "warn")
                {
                    execution.error = Some(warn_log.message.clone());
                } else if res.response.status >= 500 {
                    execution.error = Some("Internal Server Error (500)".to_string());
                }
            }

            println!(
                "\n  \x1b[1mreplaying {}\x1b[0m",
                args.replay.as_ref().unwrap()
            );
            println!("  \x1b[32m✓\x1b[0m \x1b[2musing updated code\x1b[0m");

            println!("\n  ────────────────────────────\n");
            println!("  \x1b[1mSTEP 0 — {} {}\x1b[0m\n", trace.method, trace.path);

            if let Ok(mut input_val) = serde_json::from_str::<serde_json::Value>(&body) {
                decode_flux_b64_in_value(&mut input_val);
                println!("  \x1b[1minput\x1b[0m");
                if let Some(obj) = input_val.as_object() {
                    for (k, v) in obj {
                        println!("    {}: {}", k, v);
                    }
                } else {
                    println!("    {}", input_val);
                }
                println!();
            }

            let original_reached_db = trace.checkpoints.iter().any(|c| c.boundary == "postgres");

            println!("  \x1b[1mexecution\x1b[0m");
            if original_failed {
                if original_reached_db {
                    println!("    \x1b[31m✗\x1b[0m original execution failed during/after DB step");
                } else {
                    println!("    \x1b[31m✗\x1b[0m original execution failed before reaching external IO");
                }
            } else {
                println!("    \x1b[32m✓\x1b[0m original execution succeeded");
            }

            if let Some(ref _boundary) = boundary_stop {
                println!("    \x1b[32m✓\x1b[0m replay progressed beyond original failure point");
            } else if execution.status == "error" {
                println!("    \x1b[31m✗\x1b[0m replay execution failed");
            } else if execution.status == "ok" {
                println!("    \x1b[32m✓\x1b[0m replay execution succeeded");
            }

            if let Some(error) = execution.error.as_ref() {
                println!("\n  \x1b[1merror\x1b[0m");
                println!("    \x1b[31m✗\x1b[0m {}", prettify_error(error));
                if let Some(explanation) = get_explanation(error) {
                    println!("\n    \x1b[1mexplanation\x1b[0m");
                    println!("      {}", explanation.replace("\n", "\n      "));
                }
            }

            // Print summary
            println!("\n  ────────────────────────────\n");

            if let Some(ref boundary) = boundary_stop {
                // ⏸ BOUNDARY STOP — the clean, expected outcome when replay reaches uncharted IO
                println!(
                    "  \x1b[33m⏸\x1b[0m \x1b[1mstopped at external boundary: {}\x1b[0m",
                    boundary.to_uppercase()
                );
                println!();
                println!("  \x1b[2mreason\x1b[0m");
                println!(
                    "    no recorded checkpoint available for this {} call",
                    boundary
                );
                println!("    replay never touches the real world");
                println!();

                if original_failed {
                    println!("  \x1b[1mprogress vs original\x1b[0m");
                    if original_reached_db {
                        println!("    original: reached {} → failed", boundary.to_uppercase());
                        println!(
                            "    replay:   reached {} boundary → stopped cleanly",
                            boundary.to_uppercase()
                        );
                    } else {
                        println!(
                            "    original: failed before {} boundary",
                            boundary.to_uppercase()
                        );
                        println!(
                            "    replay:   reached {} boundary → stopped cleanly",
                            boundary.to_uppercase()
                        );
                        println!();
                        println!("  \x1b[32m✓\x1b[0m your code fix is working — replay progressed further than the original");
                    }
                    println!();
                }

                println!("  \x1b[1mnext\x1b[0m");
                println!(
                    "    → run \x1b[1mflux resume {}\x1b[0m to continue with real IO",
                    args.replay.as_deref().unwrap_or("")
                );
            } else if execution.status == "ok" {
                println!("  \x1b[1mresult\x1b[0m");
                println!("    \x1b[32m✓\x1b[0m \x1b[1mreplay successful\x1b[0m");
                println!("\n  \x1b[1mnext steps\x1b[0m");
                println!(
                    "    → run \x1b[1mflux resume {}\x1b[0m to apply with real IO",
                    args.replay.as_deref().unwrap_or("")
                );
            } else {
                println!("  \x1b[1mresult\x1b[0m");
                if is_server_mode {
                    let status = execution
                        .body
                        .get("net_response")
                        .and_then(|n| n.get("status"))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(500);
                    println!(
                        "    \x1b[31m✗\x1b[0m \x1b[1mreplay failed ({})\x1b[0m",
                        status
                    );
                } else {
                    println!("    \x1b[31m✗\x1b[0m \x1b[1mexecution failed\x1b[0m");
                }

                if original_failed && execution.status == "error" {
                    println!("\n  \x1b[1mdifference vs original\x1b[0m");
                    let replay_reached_db = execution
                        .checkpoints
                        .iter()
                        .any(|c| c.boundary == "postgres");
                    if original_reached_db {
                        println!("    original: reached DB → failed");
                        println!("    replay:   reached DB → reproduced same failure");

                        println!("\n  \x1b[1minsight\x1b[0m");
                        println!("    Replay perfectly reproduced the original failure");
                        println!("    using the recorded database response.");
                    } else if !original_reached_db && replay_reached_db {
                        println!("    original: stopped before DB");
                        println!("    replay:   reached DB → failed due to new error");

                        println!("\n  \x1b[1minsight\x1b[0m");
                        println!("    Replay continued execution past the original failure");
                        println!("    and exposed a new issue.");
                    } else {
                        println!("    original: failed");
                        println!("    replay:   failed");
                    }
                }

                println!("\n  \x1b[1mnext steps\x1b[0m");
                if let Some(err) = execution.error.as_ref() {
                    if let Some(suggestion) = get_smart_suggestion(err) {
                        println!("    → {}", suggestion.replace("\n", "\n    "));
                    } else if err.contains("relation") && err.contains("does not exist") {
                        println!("    → fix database schema by creating the missing table");
                    } else if err.contains("Connection refused") {
                        println!("    → check if your database/service is running");
                    } else {
                        println!("    → fix the bug in your code");
                    }
                } else {
                    println!("    → examine the code above to identify the issue");
                }
                println!(
                    "    → then re-run:\n       flux replay {}",
                    args.replay.as_deref().unwrap_or_default()
                );
            }

            return Ok(());
        } else {
            let input: serde_json::Value = serde_json::from_str(input_str)
                .with_context(|| format!("invalid input JSON: {}", input_str))?;

            let res = isolate
                .execute_with_recorded(input.clone(), boot_context.clone(), recorded_checkpoints)
                .await?;

            runtime::isolate_pool::ExecutionResult {
                execution_id: boot_context.execution_id.clone(),
                request_id: boot_context.request_id.clone(),
                project_id: args.project_id.clone(),
                code_version: boot_context.code_version.clone(),
                status: if res.error.is_some() {
                    "error".to_string()
                } else {
                    "ok".to_string()
                },
                body: res.output,
                error: res.error,
                duration_ms: std::cmp::max(1, started.elapsed().as_millis() as i32),
                checkpoints: res.checkpoints,
                logs: res.logs,
                has_live_io: res.has_live_io,
                boundary_stop: None,

                // Advanced Telemetry
                client_ip: None,
                user_agent: None,
                request_method: None,
                request_headers: None,
                request_body: None,
                response_status: None,
                response_body: None,
                error_name: res.error_name,
                error_message: res.error_message,
                error_stack: res.error_stack,
                error_phase: res.error_phase,
                is_user_code: res.is_user_code,
                error_source: res.error_source,
                error_type: res.error_type,
                error_fingerprint: None,
            }
        };

        if !args.token.is_empty() {
            let _ = runtime::server_client::record_execution(
                &args.server_url,
                &args.token,
                runtime::server_client::ExecutionEnvelope {
                    method: if is_server_mode {
                        "REPLAY_HTTP".to_string()
                    } else {
                        "REPLAY_RUN".to_string()
                    },
                    path: args.entry.clone().unwrap_or_else(|| "index".to_string()),
                    project_id: args.project_id.clone(),
                    request_json: serde_json::Value::String(input_str.clone()),
                    result: execution.clone(),
                },
            )
            .await;
        }

        if let Some(error) = execution.error.as_ref() {
            eprintln!("error: {error}");
        }

        // Print output summary like in the CLI
        println!("\n  ────────────────────────────\n");

        if execution.status == "ok" {
            println!("  \x1b[1mresult\x1b[0m");
            println!("    \x1b[32m✓\x1b[0m \x1b[1mreplay successful\x1b[0m");
        } else {
            println!("  \x1b[1mresult\x1b[0m");
            if is_server_mode {
                let status = execution
                    .body
                    .get("net_response")
                    .and_then(|n| n.get("status"))
                    .and_then(|v| v.as_u64())
                    .unwrap_or(500);
                println!(
                    "    \x1b[31m✗\x1b[0m \x1b[1mrequest failed ({})\x1b[0m",
                    status
                );
            } else {
                println!("    \x1b[31m✗\x1b[0m \x1b[1mexecution failed\x1b[0m");
            }

            println!("\n  \x1b[1mnext steps\x1b[0m");
            if let Some(err) = execution.error.as_ref() {
                if let Some(suggestion) = get_smart_suggestion(err) {
                    println!("    → {}", suggestion);
                } else if err.contains("relation") && err.contains("does not exist") {
                    println!("    → fix database schema (create missing tables)");
                } else if err.contains("Connection refused") {
                    println!("    → check if your database/service is running");
                } else {
                    println!("    → fix the bug in your code");
                }
            } else {
                println!("    → examine the logs above to identify the issue");
            }
            println!(
                "    → then re-run:\n       flux replay {}",
                args.replay.as_deref().unwrap_or_default()
            );
        }
        return Ok(());
    }

    // 2. Decide whether to stay alive as a server or exit.
    if is_server_mode || has_handler || args.serve {
        println!("status:   serving");
        runtime::run_http_runtime(
            runtime::HttpRuntimeConfig {
                host: args.host,
                port: args.port,
                route_name,
                isolate_pool_size: args.isolate_pool_size,
                project_id: args.project_id,
                server_url: args.server_url,
                service_token: args.token,
            },
            artifact,
        )
        .await?;
    } else {
        println!("status:   finished");
    }

    Ok(())
}

fn load_entry_code(entry: &Path) -> Result<String> {
    match extension(entry).as_deref() {
        Some("js") | Some("mjs") | Some("cjs") => std::fs::read_to_string(entry)
            .with_context(|| format!("failed to read {}", entry.display())),
        Some("ts") | Some("tsx") => transpile_typescript(entry),
        _ => bail!("unsupported entry type: {}", entry.display()),
    }
}

fn extension(path: &Path) -> Option<String> {
    path.extension()
        .and_then(|v| v.to_str())
        .map(|v| v.to_ascii_lowercase())
}

fn transpile_typescript(entry: &Path) -> Result<String> {
    let source = std::fs::read_to_string(entry)
        .with_context(|| format!("failed to read {}", entry.display()))?;

    let media_type = match extension(entry).as_deref() {
        Some("tsx") => MediaType::Tsx,
        _ => MediaType::TypeScript,
    };

    // Build a file:// specifier so SWC has a meaningful path in diagnostics.
    let specifier = url::Url::from_file_path(entry)
        .unwrap_or_else(|_| url::Url::parse("file:///input.ts").unwrap());

    let parsed = deno_ast::parse_module(ParseParams {
        specifier,
        text: source.into(),
        media_type,
        capture_tokens: false,
        scope_analysis: false,
        maybe_syntax: None,
    })
    .with_context(|| format!("failed to parse {}", entry.display()))?;

    let result = parsed
        .transpile(
            &TranspileOptions::default(),
            &TranspileModuleOptions::default(),
            &EmitOptions::default(),
        )
        .with_context(|| format!("failed to transpile {}", entry.display()))?;

    Ok(result.into_source().text)
}

fn decode_flux_b64_in_value(val: &mut serde_json::Value) {
    match val {
        serde_json::Value::String(s) if s.starts_with("__FLUX_B64:") => {
            if let Some(decoded) = decode_flux_b64(s) {
                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&decoded) {
                    *val = json;
                } else {
                    *val = serde_json::Value::String(decoded);
                }
            }
        }
        serde_json::Value::Object(map) => {
            for v in map.values_mut() {
                decode_flux_b64_in_value(v);
            }
        }
        serde_json::Value::Array(arr) => {
            for v in arr.iter_mut() {
                decode_flux_b64_in_value(v);
            }
        }
        _ => {}
    }
}

fn prettify_error(err: &str) -> String {
    if err.contains("relation") && err.contains("does not exist") {
        if let Some(table) = err.split('"').nth(1) {
            return format!("DB ERROR: relation \"{}\" does not exist", table);
        }
        return "DB ERROR: table does not exist".to_string();
    }
    if err.contains("postgres connect failed") || err.contains("db error") {
        return "DB ERROR: connection failed".to_string();
    }
    if err.contains("Connection refused") {
        return "NETWORK ERROR: could not connect to service".to_string();
    }
    if err.contains("ZodError") || err.contains("invalid input") {
        return "VALIDATION ERROR: input schema mismatch".to_string();
    }
    err.to_string()
}

fn get_explanation(err: &str) -> Option<String> {
    if err.contains("relation") && err.contains("does not exist") {
        let table = err.split('"').nth(1).unwrap_or("orders");
        return Some(format!(
            "The table \"{}\" does not exist in your database.\n\
             Replay reached this step after your code fix, but\n\
             the schema is missing.",
            table
        ));
    }
    if err.contains("postgres connect failed") || err.contains("db error") {
        return Some("Flux could not connect to your database. This usually means the DATABASE_URL is incorrect or the database is not reachable.".to_string());
    }
    None
}

fn get_smart_suggestion(err: &str) -> Option<String> {
    if err.contains("relation") && err.contains("does not exist") {
        let table = err.split('"').nth(1).unwrap_or("unknown");
        return Some(format!(
            "fix your database schema by creating the missing table \"{}\"",
            table
        ));
    }
    if err.contains("postgres connect failed") || err.contains("db error") {
        return Some(
            "verify your DATABASE_URL environment variable and ensure your database is running."
                .to_string(),
        );
    }
    None
}

fn decode_flux_b64(s: &str) -> Option<String> {
    if let Some(b64) = s.strip_prefix("__FLUX_B64:") {
        use base64::Engine;
        if let Ok(bytes) = base64::engine::general_purpose::STANDARD.decode(b64) {
            if let Ok(text) = String::from_utf8(bytes) {
                return Some(text);
            }
        }
    }
    None
}
