use std::path::{Path, PathBuf};
use std::time::Instant;

use anyhow::{Context, Result, bail};
use clap::Parser;
use deno_ast::{EmitOptions, MediaType, ParseParams, TranspileModuleOptions, TranspileOptions};
use runtime::isolate_pool::{ExecutionContext, ExecutionResult};

#[derive(Parser, Debug)]
#[command(name = "flux-runtime")]
#[command(
    about = "Flux runtime — runs user JS handlers and streams execution records to flux-server"
)]
struct Args {
    /// Entry file to serve (JS, MJS, CJS, TS, or TSX).
    #[arg(long, value_name = "FILE", default_value = "index.js")]
    entry: String,

    /// Deterministic build artifact generated by `flux build`.
    #[arg(long, value_name = "FILE")]
    artifact: Option<String>,

    /// URL of the flux-server gRPC endpoint.
    #[arg(long, value_name = "URL", default_value = "http://127.0.0.1:50051")]
    server_url: String,

    /// Service token for authenticating with flux-server.
    #[arg(
        long,
        env = "FLUX_SERVICE_TOKEN",
        value_name = "TOKEN",
        default_value = ""
    )]
    token: String,

    /// HTTP listen host.
    #[arg(long, default_value = "127.0.0.1")]
    host: String,

    /// HTTP listen port.
    #[arg(long, default_value_t = 3000)]
    port: u16,

    /// Number of V8 isolates to keep warm.
    #[arg(long, default_value_t = 16)]
    isolate_pool_size: usize,

    /// Force the runtime to stay alive as an HTTP listener even if Deno.serve()
    /// was not called (e.g. to serve an exported default handler).
    #[arg(long)]
    serve: bool,

    /// JSON input passed to the exported default handler for a one-off execution.
    /// If provided, the runtime will execute the handler once and then exit.
    #[arg(long, value_name = "JSON")]
    script_input: Option<String>,

    /// Project ID for this execution.
    #[arg(long, env = "FLUX_PROJECT_ID", value_name = "ID")]
    project_id: Option<String>,
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .init();

    let args = Args::parse();

    let (artifact, route_name) = if let Some(artifact_path) = &args.artifact {
        let artifact = runtime::load_built_artifact_from_file(artifact_path)
            .map_err(|err| anyhow::anyhow!(err))?;
        let route_name = match &artifact {
            runtime::RuntimeArtifact::Built(artifact) => artifact.route_name.clone(),
            runtime::RuntimeArtifact::Inline(_) => {
                unreachable!("built artifact loader returned inline artifact")
            }
        };
        (artifact, route_name)
    } else {
        let entry = PathBuf::from(&args.entry);
        if !entry.exists() {
            bail!("entry file not found: {}", entry.display());
        }

        match extension(&entry).as_deref() {
            Some("js") | Some("mjs") | Some("cjs") | Some("ts") | Some("tsx") => {}
            _ => bail!("unsupported entry file extension: {}", entry.display()),
        }

        let canonical_entry = entry
            .canonicalize()
            .with_context(|| format!("failed to resolve entry path: {}", entry.display()))?;

        // If we have a script_input, we skip the CWD check because the runner
        // might write a temp file.
        if args.script_input.is_none() {
            let cwd = std::env::current_dir().context("failed to read current directory")?;
            let canonical_cwd = cwd
                .canonicalize()
                .context("failed to resolve current directory")?;
            if !canonical_entry.starts_with(&canonical_cwd) {
                bail!(
                    "entry file must be within the working directory: {} is outside {}",
                    canonical_entry.display(),
                    canonical_cwd.display()
                );
            }
        }

        let name = entry
            .file_name()
            .and_then(|v| v.to_str())
            .ok_or_else(|| anyhow::anyhow!("invalid entry file name: {}", entry.display()))?;

        let code = load_entry_code(&entry)?;
        let artifact = runtime::build_artifact(name, code);
        let route_name = entry
            .file_stem()
            .and_then(|v| v.to_str())
            .unwrap_or("index")
            .to_string();

        (artifact, route_name)
    };

    println!("server:   {}", args.server_url);
    if let Some(path) = &args.artifact {
        println!("artifact: {}", path);
    } else {
        println!("entry:    {}", args.entry);
    }
    println!("hash:     {}", artifact.code_version());
    println!("bytes:    {}", artifact.size_bytes());

    // Boot the project to detect if it's a server or a one-shot handler.
    let boot_context = ExecutionContext::with_project(artifact.code_version().to_string(), args.project_id.clone());
    println!("[boot] execution_id={} request_id={}", boot_context.execution_id, boot_context.request_id);
    
    let boot = runtime::boot_runtime_artifact(&artifact, boot_context.clone()).await?;

    let is_server_mode = boot.is_server_mode;
    let has_handler = boot.has_handler;

    if is_server_mode {
        println!(
            "runtime:  http://{}:{}/ (Deno.serve mode)",
            args.host, args.port
        );
    } else if has_handler {
        println!(
            "runtime:  http://{}:{}/{} (handler mode)",
            args.host, args.port, route_name
        );
    }

    // Capture the boot result if recording is enabled.
    if !args.token.is_empty() {
        let _ = runtime::server_client::record_execution(
            &args.server_url,
            &args.token,
            runtime::server_client::ExecutionEnvelope {
                method: "BOOT".to_string(),
                path: "/__boot".to_string(),
                project_id: args.project_id.clone(),
                request_json: serde_json::json!({ "phase": "boot" }),
                result: boot.result.clone(),
            },
        )
        .await;
    }

    if let Some(error) = boot.result.error.as_ref() {
        eprintln!("error: boot failed: {error}");
        if !is_server_mode && !has_handler {
            return Ok(());
        }
    }

    // 1. If script_input is provided, execute the handler once and exit.
    if let Some(input_str) = &args.script_input {
        if !has_handler {
            return Ok(());
        }

        let input: serde_json::Value = serde_json::from_str(input_str)
            .with_context(|| format!("invalid --script-input JSON: {}", input_str))?;

        let mut isolate = runtime::JsIsolate::new_from_any_artifact(&artifact, 0).await?;

        let started = Instant::now();
        let execution = isolate
            .execute_handler(input.clone(), boot_context.clone())
            .await?;

        if !args.token.is_empty() {
            let result = ExecutionResult {
                execution_id: boot_context.execution_id.clone(),
                request_id: boot_context.request_id.clone(),
                project_id: args.project_id.clone(),
                code_version: boot_context.code_version.clone(),
                status: if execution.error.is_some() {
                    "error".to_string()
                } else {
                    "ok".to_string()
                },
                body: execution.output.clone(),
                error: execution.error.clone(),
                duration_ms: started.elapsed().as_millis() as i32,
                checkpoints: execution.checkpoints.clone(),
                logs: execution.logs.clone(),
            };

            let _ = runtime::server_client::record_execution(
                &args.server_url,
                &args.token,
                runtime::server_client::ExecutionEnvelope {
                    method: "RUN".to_string(),
                    path: args.entry.clone(),
                    project_id: args.project_id.clone(),
                    request_json: input,
                    result,
                },
            )
            .await;
        }

        if let Some(error) = execution.error.as_ref() {
            eprintln!("error: {error}");
        }
        if !execution.output.is_null() {
            println!(
                "{}",
                serde_json::to_string_pretty(&execution.output).unwrap_or_default()
            );
        }
        return Ok(());
    }

    // 2. Decide whether to stay alive as a server or exit.
    if is_server_mode || has_handler || args.serve {
        println!("status:   serving");
        runtime::run_http_runtime(
            runtime::HttpRuntimeConfig {
                host: args.host,
                port: args.port,
                route_name,
                isolate_pool_size: args.isolate_pool_size,
                project_id: args.project_id,
                server_url: args.server_url,
                service_token: args.token,
            },
            artifact,
        )
        .await?;
    } else {
        println!("status:   finished");
    }

    Ok(())
}

fn load_entry_code(entry: &Path) -> Result<String> {
    match extension(entry).as_deref() {
        Some("js") | Some("mjs") | Some("cjs") => std::fs::read_to_string(entry)
            .with_context(|| format!("failed to read {}", entry.display())),
        Some("ts") | Some("tsx") => transpile_typescript(entry),
        _ => bail!("unsupported entry type: {}", entry.display()),
    }
}

fn extension(path: &Path) -> Option<String> {
    path.extension()
        .and_then(|v| v.to_str())
        .map(|v| v.to_ascii_lowercase())
}

fn transpile_typescript(entry: &Path) -> Result<String> {
    let source = std::fs::read_to_string(entry)
        .with_context(|| format!("failed to read {}", entry.display()))?;

    let media_type = match extension(entry).as_deref() {
        Some("tsx") => MediaType::Tsx,
        _ => MediaType::TypeScript,
    };

    // Build a file:// specifier so SWC has a meaningful path in diagnostics.
    let specifier = url::Url::from_file_path(entry)
        .unwrap_or_else(|_| url::Url::parse("file:///input.ts").unwrap());

    let parsed = deno_ast::parse_module(ParseParams {
        specifier,
        text: source.into(),
        media_type,
        capture_tokens: false,
        scope_analysis: false,
        maybe_syntax: None,
    })
    .with_context(|| format!("failed to parse {}", entry.display()))?;

    let result = parsed
        .transpile(
            &TranspileOptions::default(),
            &TranspileModuleOptions::default(),
            &EmitOptions::default(),
        )
        .with_context(|| format!("failed to transpile {}", entry.display()))?;

    Ok(result.into_source().text)
}
