use std::path::{Path, PathBuf};
use std::time::Instant;

use anyhow::{Context, Result, bail};
use clap::Parser;
use deno_ast::{EmitOptions, MediaType, ParseParams, TranspileModuleOptions, TranspileOptions};
use runtime::isolate_pool::ExecutionContext;

#[derive(Parser, Debug)]
#[command(name = "flux-runtime")]
#[command(
    about = "Flux runtime — runs user JS handlers and streams execution records to flux-server"
)]
struct Args {
    /// Entry file to serve (JS, MJS, CJS, TS, or TSX).
    #[arg(long, value_name = "FILE", default_value = "index.js")]
    entry: String,

    /// Deterministic build artifact generated by `flux build`.
    #[arg(long, value_name = "FILE")]
    artifact: Option<String>,

    /// URL of the flux-server gRPC endpoint.
    #[arg(long, value_name = "URL", default_value = "http://127.0.0.1:50051")]
    server_url: String,

    /// Service token for authenticating with flux-server.
    #[arg(
        long,
        env = "FLUX_SERVICE_TOKEN",
        value_name = "TOKEN",
        default_value = ""
    )]
    token: String,

    /// HTTP listen host.
    #[arg(long, default_value = "127.0.0.1")]
    host: String,

    /// HTTP listen port.
    #[arg(long, default_value_t = 3000)]
    port: u16,

    /// Number of V8 isolates to keep warm.
    #[arg(long, default_value_t = 16)]
    isolate_pool_size: usize,

    /// Force the runtime to stay alive as an HTTP listener even if Deno.serve()
    /// was not called (e.g. to serve an exported default handler).
    #[arg(long)]
    serve: bool,

    /// JSON input passed to the exported default handler for a one-off execution.
    /// If provided, the runtime will execute the handler once and then exit.
    #[arg(long, value_name = "JSON")]
    script_input: Option<String>,

    /// Project ID for this execution.
    #[arg(long, env = "FLUX_PROJECT_ID", value_name = "ID")]
    project_id: Option<String>,

    /// Print raw console logs from the replayed execution.
    #[arg(long)]
    verbose: bool,

    /// Execution ID to replay. If provided, the runtime fetches recorded
    /// checkpoints for this ID and runs the local code against them.
    #[arg(long, value_name = "ID")]
    replay: Option<String>,
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .init();

    let args = Args::parse();

    let (artifact, route_name) = if let Some(artifact_path) = &args.artifact {
        let artifact = runtime::load_built_artifact_from_file(artifact_path)
            .map_err(|err| anyhow::anyhow!(err))?;
        let route_name = match &artifact {
            runtime::RuntimeArtifact::Built(artifact) => artifact.route_name.clone(),
            runtime::RuntimeArtifact::Inline(_) => {
                unreachable!("built artifact loader returned inline artifact")
            }
        };
        (artifact, route_name)
    } else {
        let entry = PathBuf::from(&args.entry);
        if !entry.exists() {
            bail!("entry file not found: {}", entry.display());
        }

        match extension(&entry).as_deref() {
            Some("js") | Some("mjs") | Some("cjs") | Some("ts") | Some("tsx") => {}
            _ => bail!("unsupported entry file extension: {}", entry.display()),
        }

        let canonical_entry = entry
            .canonicalize()
            .with_context(|| format!("failed to resolve entry path: {}", entry.display()))?;

        // If we have a script_input, we skip the CWD check because the runner
        // might write a temp file.
        if args.script_input.is_none() {
            let cwd = std::env::current_dir().context("failed to read current directory")?;
            let canonical_cwd = cwd
                .canonicalize()
                .context("failed to resolve current directory")?;
            if !canonical_entry.starts_with(&canonical_cwd) {
                bail!(
                    "entry file must be within the working directory: {} is outside {}",
                    canonical_entry.display(),
                    canonical_cwd.display()
                );
            }
        }

        let name = entry
            .file_name()
            .and_then(|v| v.to_str())
            .ok_or_else(|| anyhow::anyhow!("invalid entry file name: {}", entry.display()))?;

        let code = load_entry_code(&entry)?;
        let artifact = runtime::build_artifact(name, code);
        let route_name = entry
            .file_stem()
            .and_then(|v| v.to_str())
            .unwrap_or("index")
            .to_string();

        (artifact, route_name)
    };

    if args.replay.is_none() {
        println!("server:   {}", args.server_url);
        if let Some(path) = &args.artifact {
            println!("artifact: {}", path);
        } else {
            println!("entry:    {}", args.entry);
        }
    }
    if args.replay.is_none() {
        println!("hash:     {}", artifact.code_version());
        println!("bytes:    {}", artifact.size_bytes());
    }

    // Boot the project to detect if it's a server or a one-shot handler.
    let mut boot_context = ExecutionContext::with_project(artifact.code_version().to_string(), args.project_id.clone());
    boot_context.verbose = args.verbose;
    
    let mut recorded_checkpoints = Vec::new();
    let mut replay_input = args.script_input.clone();

    let mut replay_trace = None;

    if let Some(ref replay_id) = args.replay {
        if args.token.is_empty() {
            // println!("replay:   {}", replay_id);
        }
        let trace = runtime::server_client::get_trace(&args.server_url, &args.token, replay_id).await?;
        recorded_checkpoints = trace.checkpoints.iter().map(|cp| {
            runtime::deno_runtime::FetchCheckpoint {
                call_index: cp.call_index as u32,
                boundary: cp.boundary.clone(),
                url: String::new(),
                method: String::new(),
                request: serde_json::from_slice(&cp.request).unwrap_or(serde_json::Value::Null),
                response: serde_json::from_slice(&cp.response).unwrap_or(serde_json::Value::Null),
                duration_ms: cp.duration_ms,
            }
        }).collect();
        
        boot_context.mode = runtime::deno_runtime::ExecutionMode::Replay;
        
        if replay_input.is_none() {
            replay_input = Some(trace.request_json.clone());
        }
        replay_trace = Some(trace);
    }

    if args.verbose {
        println!("[boot] execution_id={} request_id={}", boot_context.execution_id, boot_context.request_id);
    }
    
    let boot = runtime::boot_runtime_artifact(&artifact, boot_context.clone()).await?;

    let is_server_mode = boot.is_server_mode;
    let has_handler = boot.has_handler;

    if args.replay.is_none() {
        if is_server_mode {
            println!(
                "runtime:  http://{}:{}/ (Deno.serve mode)",
                args.host, args.port
            );
        } else if has_handler {
            println!(
                "runtime:  http://{}:{}/{} (handler mode)",
                args.host, args.port, route_name
            );
        }
    }

    // Capture the boot result if recording is enabled.
    if !args.token.is_empty() {
        let _ = runtime::server_client::record_execution(
            &args.server_url,
            &args.token,
            runtime::server_client::ExecutionEnvelope {
                method: "BOOT".to_string(),
                path: "/__boot".to_string(),
                project_id: args.project_id.clone(),
                request_json: serde_json::json!({ "phase": "boot" }),
                result: boot.result.clone(),
            },
        )
        .await;
    }

    if let Some(error) = boot.result.error.as_ref() {
        eprintln!("error: boot failed: {error}");
        if !is_server_mode && !has_handler {
            return Ok(());
        }
    }    // 1. If script_input or replay is provided, execute the handler once and exit.
    if let Some(input_str) = &replay_input {
        if !has_handler && !is_server_mode {
            return Ok(());
        }

        let mut isolate = runtime::JsIsolate::new_from_any_artifact(&artifact, 0).await?;
        let started = Instant::now();

        let execution = if is_server_mode {
            let trace = replay_trace.as_ref().ok_or_else(|| anyhow::anyhow!("replay trace missing for server-mode replay"))?;

            // Intelligent unpacking: Flux HTTP executions record an envelope.
            // If the request_json looks like an envelope, extract the real body and headers.
            let (body, headers_json) = if let Ok(envelope) = serde_json::from_str::<serde_json::Value>(&trace.request_json) {
                if envelope.get("method").is_some() && envelope.get("url").is_some() && envelope.get("body").is_some() {
                    let b = envelope.get("body").and_then(|v| v.as_str()).unwrap_or("").to_string();
                    let h = serde_json::to_string(envelope.get("headers").unwrap_or(&serde_json::json!([]))).unwrap_or_else(|_| "[]".to_string());
                    (b, h)
                } else {
                    (trace.request_json.clone(), "[[\"content-type\", \"application/json\"]]".to_string())
                }
            } else {
                (trace.request_json.clone(), "[[\"content-type\", \"application/json\"]]".to_string())
            };

            let original_failed = trace.status != "ok";
            let net_req = runtime::deno_runtime::NetRequest {
                req_id: boot_context.request_id.clone(),
                method: trace.method.clone(),
                url: format!("http://localhost{}", trace.path),
                headers_json,
                body: body.clone(),
            };

            let res = isolate.dispatch_request_with_recorded(boot_context.clone(), net_req, recorded_checkpoints).await?;
            let mut execution = runtime::isolate_pool::ExecutionResult {
                execution_id: boot_context.execution_id.clone(),
                request_id: boot_context.request_id.clone(),
                project_id: args.project_id.clone(),
                code_version: boot_context.code_version.clone(),
                status: if res.response.status >= 400 { "error".to_string() } else { "ok".to_string() },
                body: serde_json::json!({
                    "status": res.response.status,
                    "headers": res.response.headers,
                    "body": res.response.body,
                }),
                error: res.error,
                duration_ms: 0, 
                checkpoints: res.checkpoints,
                logs: res.logs,
                has_live_io: res.has_live_io,
            };

            // Robust error capture: fallback to logs if error is missing but status is error
            if execution.error.is_none() && execution.status == "error" {
                if let Some(error_log) = execution.logs.iter().rev().find(|l| l.level == "error") {
                    execution.error = Some(error_log.message.clone());
                } else if let Some(warn_log) = execution.logs.iter().rev().find(|l| l.level == "warn") {
                    execution.error = Some(warn_log.message.clone());
                } else if res.response.status >= 500 {
                     execution.error = Some("Internal Server Error (500)".to_string());
                }
            }

            println!("\n  \x1b[1mreplaying {}\x1b[0m", args.replay.as_ref().unwrap());
            println!("  \x1b[32m✓\x1b[0m \x1b[2musing updated code\x1b[0m");
            if execution.has_live_io {
                println!("  \x1b[33m⚠\x1b[0m \x1b[2mpartial replay (live IO used)\x1b[0m");
            }
            
            println!("\n  ────────────────────────────\n");
            println!("  \x1b[1mSTEP 0 — {} {}\x1b[0m\n", trace.method, trace.path);

            if let Ok(mut input_val) = serde_json::from_str::<serde_json::Value>(&body) {
                 decode_flux_b64_in_value(&mut input_val);
                 println!("  \x1b[1minput\x1b[0m");
                 if let Some(obj) = input_val.as_object() {
                     for (k, v) in obj {
                         println!("    {}: {}", k, v);
                     }
                 } else {
                     println!("    {}", input_val);
                 }
                 println!();
            }

            println!("  \x1b[1mexecution\x1b[0m");
            if original_failed {
                println!("    \x1b[31m✗\x1b[0m original execution failed before DB step");
            } else {
                println!("    \x1b[32m✓\x1b[0m original execution succeeded");
            }
            
            if execution.status == "error" && original_failed && execution.has_live_io {
                 println!("    \x1b[32m→\x1b[0m replay progressed further and reached DB");
            } else if execution.status == "error" {
                 println!("    \x1b[31m✗\x1b[0m replay execution failed");
            } else if execution.has_live_io && !original_failed {
                 // Reached DB even though original didn't fail? (e.g. code changed to reach it)
                 println!("    \x1b[32m→\x1b[0m reached database (not reached in original execution)");
            }

            if execution.has_live_io {
                println!("\n  \x1b[1mio\x1b[0m");
                println!("    \x1b[33m⚠\x1b[0m \x1b[1mLIVE database query\x1b[0m");
                println!("      reason: original execution never reached this step");
                println!("      note: no recorded checkpoint available");
            }

            if let Some(error) = execution.error.as_ref() {
                println!("\n  \x1b[1merror\x1b[0m");
                println!("    \x1b[31m✗\x1b[0m {}", prettify_error(error));
                if let Some(explanation) = get_explanation(error) {
                    println!("\n    \x1b[1mexplanation\x1b[0m");
                    println!("      {}", explanation.replace("\n", "\n      "));
                }
            }

            // Print summary
            println!("\n  ────────────────────────────\n");

            if execution.status == "ok" {
                println!("  \x1b[1mresult\x1b[0m");
                println!("    \x1b[32m✓\x1b[0m \x1b[1mreplay successful\x1b[0m");
            } else {
                println!("  \x1b[1mresult\x1b[0m");
                if is_server_mode {
                    let status = execution.body.get("net_response").and_then(|n| n.get("status")).and_then(|v| v.as_u64()).unwrap_or(500);
                    println!("    \x1b[31m✗\x1b[0m \x1b[1mrequest failed ({})\x1b[0m", status);
                } else {
                    println!("    \x1b[31m✗\x1b[0m \x1b[1mexecution failed\x1b[0m");
                }

                if original_failed && execution.status == "error" {
                    println!("\n  \x1b[1mdifference vs original\x1b[0m");
                    println!("    original: stopped before DB");
                    println!("    replay:   reached DB → failed due to missing table");

                    println!("\n  \x1b[1minsight\x1b[0m");
                    println!("    Replay continued execution past the original failure");
                    println!("    and exposed a database schema issue.");
                }

                println!("\n  \x1b[1mnext steps\x1b[0m");
                if let Some(err) = execution.error.as_ref() {
                    if let Some(suggestion) = get_smart_suggestion(err) {
                        println!("    → {}", suggestion.replace("\n", "\n    "));
                    } else if err.contains("relation") && err.contains("does not exist") {
                        println!("    → fix database schema by creating the missing table");
                    } else if err.contains("Connection refused") {
                        println!("    → check if your database/service is running");
                    } else {
                        println!("    → fix the bug in your code");
                    }
                } else {
                    println!("    → examine the code above to identify the issue");
                }
                println!("    → then re-run:\n       flux replay {}", args.replay.as_deref().unwrap_or_default());
            }

            return Ok(());
        } else {
            let input: serde_json::Value = serde_json::from_str(input_str)
                .with_context(|| format!("invalid input JSON: {}", input_str))?;

            let res = isolate
                .execute_with_recorded(input.clone(), boot_context.clone(), recorded_checkpoints)
                .await?;
            
            runtime::isolate_pool::ExecutionResult {
                execution_id: boot_context.execution_id.clone(),
                request_id: boot_context.request_id.clone(),
                project_id: args.project_id.clone(),
                code_version: boot_context.code_version.clone(),
                status: if res.error.is_some() { "error".to_string() } else { "ok".to_string() },
                body: res.output,
                error: res.error,
                duration_ms: started.elapsed().as_millis() as i32,
                checkpoints: res.checkpoints,
                logs: res.logs,
                has_live_io: res.has_live_io,
            }
        };

        if !args.token.is_empty() {
            let _ = runtime::server_client::record_execution(
                &args.server_url,
                &args.token,
                runtime::server_client::ExecutionEnvelope {
                    method: if is_server_mode { "REPLAY_HTTP".to_string() } else { "REPLAY_RUN".to_string() },
                    path: args.entry.clone(),
                    project_id: args.project_id.clone(),
                    request_json: serde_json::Value::String(input_str.clone()),
                    result: execution.clone(),
                },
            )
            .await;
        }

        if let Some(error) = execution.error.as_ref() {
            eprintln!("error: {error}");
        }

        // Print output summary like in the CLI
        println!("\n  ────────────────────────────\n");

        if execution.status == "ok" {
            println!("  \x1b[1mresult\x1b[0m");
            println!("    \x1b[32m✓\x1b[0m \x1b[1mreplay successful\x1b[0m");
        } else {
            println!("  \x1b[1mresult\x1b[0m");
            if is_server_mode {
                let status = execution.body.get("net_response").and_then(|n| n.get("status")).and_then(|v| v.as_u64()).unwrap_or(500);
                println!("    \x1b[31m✗\x1b[0m \x1b[1mrequest failed ({})\x1b[0m", status);
            } else {
                println!("    \x1b[31m✗\x1b[0m \x1b[1mexecution failed\x1b[0m");
            }

            println!("\n  \x1b[1mnext steps\x1b[0m");
            if let Some(err) = execution.error.as_ref() {
                if let Some(suggestion) = get_smart_suggestion(err) {
                    println!("    → {}", suggestion);
                } else if err.contains("relation") && err.contains("does not exist") {
                    println!("    → fix database schema (create missing tables)");
                } else if err.contains("Connection refused") {
                    println!("    → check if your database/service is running");
                } else {
                    println!("    → fix the bug in your code");
                }
            } else {
                println!("    → examine the logs above to identify the issue");
            }
            println!("    → then re-run:\n       flux replay {}", args.replay.as_deref().unwrap_or_default());
        }
        return Ok(());
    }

    // 2. Decide whether to stay alive as a server or exit.
    if is_server_mode || has_handler || args.serve {
        println!("status:   serving");
        runtime::run_http_runtime(
            runtime::HttpRuntimeConfig {
                host: args.host,
                port: args.port,
                route_name,
                isolate_pool_size: args.isolate_pool_size,
                project_id: args.project_id,
                server_url: args.server_url,
                service_token: args.token,
            },
            artifact,
        )
        .await?;
    } else {
        println!("status:   finished");
    }

    Ok(())
}

fn load_entry_code(entry: &Path) -> Result<String> {
    match extension(entry).as_deref() {
        Some("js") | Some("mjs") | Some("cjs") => std::fs::read_to_string(entry)
            .with_context(|| format!("failed to read {}", entry.display())),
        Some("ts") | Some("tsx") => transpile_typescript(entry),
        _ => bail!("unsupported entry type: {}", entry.display()),
    }
}

fn extension(path: &Path) -> Option<String> {
    path.extension()
        .and_then(|v| v.to_str())
        .map(|v| v.to_ascii_lowercase())
}

fn transpile_typescript(entry: &Path) -> Result<String> {
    let source = std::fs::read_to_string(entry)
        .with_context(|| format!("failed to read {}", entry.display()))?;

    let media_type = match extension(entry).as_deref() {
        Some("tsx") => MediaType::Tsx,
        _ => MediaType::TypeScript,
    };

    // Build a file:// specifier so SWC has a meaningful path in diagnostics.
    let specifier = url::Url::from_file_path(entry)
        .unwrap_or_else(|_| url::Url::parse("file:///input.ts").unwrap());

    let parsed = deno_ast::parse_module(ParseParams {
        specifier,
        text: source.into(),
        media_type,
        capture_tokens: false,
        scope_analysis: false,
        maybe_syntax: None,
    })
    .with_context(|| format!("failed to parse {}", entry.display()))?;

    let result = parsed
        .transpile(
            &TranspileOptions::default(),
            &TranspileModuleOptions::default(),
            &EmitOptions::default(),
        )
        .with_context(|| format!("failed to transpile {}", entry.display()))?;

    Ok(result.into_source().text)
}

fn decode_flux_b64_in_value(val: &mut serde_json::Value) {
    match val {
        serde_json::Value::String(s) if s.starts_with("__FLUX_B64:") => {
            if let Some(decoded) = decode_flux_b64(s) {
                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&decoded) {
                    *val = json;
                } else {
                    *val = serde_json::Value::String(decoded);
                }
            }
        }
        serde_json::Value::Object(map) => {
            for v in map.values_mut() {
                decode_flux_b64_in_value(v);
            }
        }
        serde_json::Value::Array(arr) => {
            for v in arr.iter_mut() {
                decode_flux_b64_in_value(v);
            }
        }
        _ => {}
    }
}

fn prettify_error(err: &str) -> String {
    if err.contains("relation") && err.contains("does not exist") {
        if let Some(table) = err.split('"').nth(1) {
            return format!("DB ERROR: relation \"{}\" does not exist", table);
        }
        return "DB ERROR: table does not exist".to_string();
    }
    if err.contains("postgres connect failed") || err.contains("db error") {
        return "DB ERROR: connection failed".to_string();
    }
    if err.contains("Connection refused") {
        return "NETWORK ERROR: could not connect to service".to_string();
    }
    if err.contains("ZodError") || err.contains("invalid input") {
        return "VALIDATION ERROR: input schema mismatch".to_string();
    }
    err.to_string()
}

fn get_explanation(err: &str) -> Option<String> {
    if err.contains("relation") && err.contains("does not exist") {
        let table = err.split('"').nth(1).unwrap_or("orders");
        return Some(format!(
            "The table \"{}\" does not exist in your database.\n\
             Replay reached this step after your code fix, but\n\
             the schema is missing.",
            table
        ));
    }
    if err.contains("postgres connect failed") || err.contains("db error") {
        return Some("Flux could not connect to your database. This usually means the DATABASE_URL is incorrect or the database is not reachable.".to_string());
    }
    None
}

fn get_smart_suggestion(err: &str) -> Option<String> {
    if err.contains("relation") && err.contains("does not exist") {
        let table = err.split('"').nth(1).unwrap_or("unknown");
        return Some(format!("fix your database schema by creating the missing table \"{}\"", table));
    }
    if err.contains("postgres connect failed") || err.contains("db error") {
        return Some("verify your DATABASE_URL environment variable and ensure your database is running.".to_string());
    }
    None
}

fn decode_flux_b64(s: &str) -> Option<String> {
    if let Some(b64) = s.strip_prefix("__FLUX_B64:") {
        use base64::Engine;
        if let Ok(bytes) = base64::engine::general_purpose::STANDARD.decode(b64) {
            if let Ok(text) = String::from_utf8(bytes) {
                return Some(text);
            }
        }
    }
    None
}
