# Build stage
FROM rust:1.82-slim-bookworm as builder

WORKDIR /app
COPY shared ./shared
COPY server ./server

WORKDIR /app/server
RUN cargo build --release

# Runtime stage
FROM debian:bookworm-slim

WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/flux-server /usr/local/bin/flux-server

EXPOSE 3003
CMD ["flux-server"]
