// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single API key record returned by list/create endpoints.
 */
export type ApiKeyRow = { id: string, name: string, key_prefix: string, created_at: string, last_used_at: string | null, };
