// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploySummary } from "./DeploySummary";

/**
 * `POST /deployments/project` — records a multi-function deploy in one call.
 */
export type CreateProjectDeploymentPayload = { version: bigint, summary: DeploySummary, deployed_by: string | null, };
