// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `POST /functions`.
 */
export type CreateFunctionResponse = { function_id: string, name: string, runtime: string, run_url: string, };
