// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateSubscriptionPayload = { event_pattern: string, target_type: string, target_config: JsonValue | null, };
