// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /functions/{id}/deployments`
 */
export type CreateDeploymentPayload = { storage_key: string, };
