// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateRoutePayload = { method: string, path: string, function_id: string, is_async: boolean, auth_type: string, cors_enabled: boolean, rate_limit: number | null, };
