// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `POST /api-keys` — includes the full key (shown once only).
 */
export type CreateApiKeyResponse = { id: string, name: string, key_prefix: string, key: string, created_at: string, };
