// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CronJobRow = { id: string, name: string, schedule: string, action_type: string, action_config: JsonValue, enabled: boolean, last_run_at: string | null, next_run_at: string | null, created_at: string, updated_at: string, };
