// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type DeadLetterJobRow = { id: string, function_id: string | null, payload: JsonValue | null, error: string | null, failed_at: string | null, };
