// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single deployment record returned by the list/get endpoints.
 */
export type DeploymentResponse = { id: string, version: number, is_active: boolean, status: string, created_at: string, run_url: string | null, };
