// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionDeploySummaryEntry } from "./FunctionDeploySummaryEntry";

/**
 * Aggregate counts included in project deployment records.
 */
export type DeploySummary = { total: bigint, deployed: bigint, skipped: bigint, functions: Array<FunctionDeploySummaryEntry>, };
