// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type EventRow = { id: string, event_type: string, table_name: string, record_id: string | null, operation: string, payload: JsonValue, delivered_at: string | null, created_at: string, };
