// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-function result inside a project deployment summary.
 */
export type FunctionDeploySummaryEntry = { name: string, version: bigint, 
/**
 * `"deployed"` | `"skipped"` | `"failed"`
 */
status: string, };
