// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Full function record returned by list/get endpoints.
 */
export type FunctionResponse = { id: string, name: string, runtime: string, description: string | null, input_schema: JsonValue | null, output_schema: JsonValue | null, created_at: string, run_url: string, };
