// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrateResponse = { 
/**
 * `"applied"` or `"already_applied"`
 */
status: string, message: string | null, };
