// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrateRequest = { 
/**
 * Filename, e.g. `001_create_users.sql`. Used as the unique migration key.
 */
name: string, 
/**
 * Full SQL content of the migration file.
 */
content: string, };
