// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A platform log entry returned by `GET /logs`.
 *
 * `source`   — subsystem that emitted the log: `function | db | workflow | event | queue | system`
 * `resource` — resource identifier within that source (function name, table name, etc.)
 * `span_type`— span classification: `start | end | error | event`
 */
export type PlatformLogRow = { id: string, source: string, resource: string, level: string, message: string, request_id: string | null, span_type: string | null, metadata: JsonValue | null, timestamp: string, tier: string | null, };
