// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gateway routing table row — returned by `GET /routes` and `GET /internal/routes`.
 */
export type RouteConfigRow = { id: string, path: string, method: string, function_name: string, middleware: Array<string>, rate_limit_per_minute: number | null, };
