// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Extended route record with auth + CORS details (single-route GET response).
 */
export type RouteFullRow = { id: string, path: string, method: string, function_id: string, is_async: boolean, auth_type: string, cors_enabled: boolean, rate_limit: number | null, created_at: string, jwks_url: string | null, jwt_audience: string | null, jwt_issuer: string | null, cors_origins: Array<string> | null, cors_headers: Array<string> | null, };
