// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoutePayloadEntry = { path: string, method: string, function_name: string, middleware: Array<string>, rate_limit_per_minute: number | null, };
