// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Secret record — value is never included in responses.
 */
export type SecretResponse = { key: string, version: number, created_at: string, };
