// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutePayloadEntry } from "./RoutePayloadEntry";

/**
 * Bulk route sync payload sent by `flux deploy` (gateway route table refresh).
 */
export type SyncRoutesPayload = { project_deployment_id: string | null, routes: Array<RoutePayloadEntry>, };
