// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateRoutePayload = { path: string | null, method: string | null, function_id: string | null, is_async: boolean | null, auth_type: string | null, cors_enabled: boolean | null, rate_limit: number | null | null, };
