-- Links each job execution to its runtime execution record.
-- request_id is generated by the queue worker before calling the runtime and
-- forwarded as x-request-id so the runtime stores it in execution_records/spans.
-- This allows `flux trace <jobs.request_id>` to pull the full execution trace.
ALTER TABLE jobs
    ADD COLUMN IF NOT EXISTS request_id UUID;

CREATE INDEX IF NOT EXISTS idx_jobs_request_id ON jobs(request_id) WHERE request_id IS NOT NULL;
